# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  # Service 1: Your .NET Web API
  paymentapi:
    image: paymentapi
    build:
      context: .
      dockerfile: PaymentAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Overriding the connection string to talk to the 'sqlserver' container
      - ConnectionStrings__DevConnection=Server=sqlserver;Database=PaymentDetailDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  # Service 2: The SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
